[package]
edition = "2021"
name = "esfuse-compiler"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.69"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.11.1", default-features = false, features = ["napi4"] }
napi-derive = "2.11.0"
swc = "0.245.35"
swc_common = "0.29.32"
swc_core = { version = "0.59.40", features = [
  "base",
  "common",
  "ecma_ast",
  "ecma_visit",
  "ecma_transforms",
  "ecma_parser",
  "ecma_quote",
  "ecma_utils",
] }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
