[package]
edition = "2021"
name = "esfuse_bindings"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
arca = { version = "0.3.3", features = ["napi", "serde"] }
#napi-derive = { "path" = "/Users/mael.nison/napi-rs/crates/macro" }
#napi = { "path" = "/Users/mael.nison/napi-rs/crates/napi", default-features = false, features = ["napi4", "serde-json", "tokio_rt"] }
#napi-derive = { git = "https://github.com/arcanis/napi-rs.git", branch = "mael/napi-generic-types" }
#napi = { git = "https://github.com/arcanis/napi-rs.git", branch = "mael/napi-generic-types", default-features = false, features = ["napi4", "serde-json", "tokio_rt"] }
napi-derive = "2.13.0"
napi = { version = "2.13.1", default-features = false, features = ["napi4", "serde-json", "tokio_rt"] }

esfuse = { path = "../esfuse-rust" }
glob-match = "0.2.1"
serde = "1.0.157"
serde_json = "1.0.94"

[build-dependencies]
napi-build = { git = "https://github.com/arcanis/napi-rs.git", branch = "mael/napi-generic-types" }

[profile.release]
lto = true
