[package]
edition = "2021"
name = "esfuse_bindings"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
esfuse = { path = "../esfuse-rust" }
glob-match = "0.2.1"
napi = { git = "https://github.com/napi-rs/napi-rs.git", branch = "reexport-types-from-shared-crate", default-features = false, features = ["napi4", "tokio_rt"] }
napi-derive = { git = "https://github.com/napi-rs/napi-rs.git", branch = "reexport-types-from-shared-crate" }
serde = "1.0.157"
serde_json = "1.0.94"

[build-dependencies]
napi-build = { git = "https://github.com/napi-rs/napi-rs.git", branch = "reexport-types-from-shared-crate" }

[profile.release]
lto = true
