[package]
name = "esfuse"
edition = "2021"
version = "0.0.0"

[dependencies]

#mdxjs = { path = "/Users/mael.nison/mdxjs-rs" }
mdxjs = { git = "https://github.com/arcanis/mdxjs-rs.git", branch = "mael/compile_with_ast" }
#mdxjs = "0.1.8"

#napi-derive = { "path" = "/Users/mael.nison/napi-rs/crates/macro" }
#napi = { "path" = "/Users/mael.nison/napi-rs/crates/napi", default-features = false, features = ["napi4", "serde-json", "tokio_rt"] }
#napi-derive = { git = "https://github.com/arcanis/napi-rs.git", branch = "mael/napi-generic-types" }
#napi = { git = "https://github.com/arcanis/napi-rs.git", branch = "mael/napi-generic-types", default-features = false, features = ["napi4", "serde-json", "tokio_rt"] }
napi-derive = "2.13.0"
napi = { version = "2.13.1", default-features = false, features = ["napi4", "serde-json", "tokio_rt"] }

#parcel-resolver = { path = "/Users/mael.nison/parcel/packages/utils/node-resolver-rs" }
parcel-resolver = { git = "https://github.com/arcanis/parcel.git", branch = "mael/pnp" }

#pnp = { path = "/Users/mael.nison/pnp-rust" }
pnp = "0.6.0"

parcel_sourcemap = { version = "2.1.1", features = ["json"] }
queues = "1.1.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
swc = "0.245.35"
swc_common = "0.29.32"
swc_core = { version = "0.59.40", features = ["base", "common", "ecma_ast", "ecma_parser_typescript", "ecma_visit", "ecma_transforms", "ecma_parser", "ecma_quote", "ecma_utils", "ecma_visit_path"] }
thiserror = "1.0.39"
pathdiff = "0.2.1"
path-slash = "0.2.1"
clean-path = "0.2.1"
regex = "1.7.1"
fancy-regex = "0.11.0"
lazy_static = "1.4.0"
querystring = "1.1.0"
serde-querystring = "0.2.1"
markdown = "1.0.0-alpha.7"
serde_yaml = "0.9.19"
urlencoding = "2.1.2"
arca = { version = "0.3.3", features = ["napi", "serde"] }
clippy = "0.0.302"
lightningcss = "1.0.0-alpha.40"
mime_guess = "2.0.4"
tokio = { version = "1.27.0", features = ["fs", "macros", "rt-multi-thread", "rt", "sync"] }
base64 = "0.21.0"
itertools = "0.10.5"
sha1 = "0.10.5"
hex = "0.4.3"
